import os
import sqlite3
from datetime import datetime

# Define extended content for files
project_data = {
    "data/governance": {
        "gov_conduct.txt": "Our Corporate Code of Conduct mandates that all employees, contractors, and executive leadership must uphold the absolute highest standards of integrity, professional behavior, and transparency in every transaction. This comprehensive policy fosters an inclusive work environment that actively respects diverse perspectives and enforces a strict zero-tolerance stance against any form of discrimination or harassment. Furthermore, the framework explicitly prohibits all forms of anti-bribery, insider trading, and corporate corruption. Employees are formally required to disclose any potential or perceived conflicts of interest to the Human Resources and Compliance Committee within 48 hours of becoming aware of the situation. Failure to comply with these baseline ethical requirements will result in a mandatory disciplinary review, which may lead to immediate termination and, in cases of legal violations, formal referral to external regulatory authorities for prosecution.",
        "gov_remote.txt": "The Remote Work Policy outlines the essential operational expectations, security compliance requirements, and communication guidelines for all staff members who perform their duties outside of the company's primary physical office locations. Employees working in a remote capacity are held strictly responsible for ensuring that their home network environment is secured with enterprise-grade WPA3 encryption protocols and that all company-issued hardware is kept physically secure from access by unauthorized household members or third parties. To ensure seamless cross-functional collaboration and to maintain operational efficiency across differing global time zones, all remote staff members are required to observe core working hours from 10:00 AM to 4:00 PM EST. Regular participation in daily departmental stand-ups and periodic digital check-ins is mandatory. Any failure to maintain these reliable communication channels or repeated instances of unexcused absences during core hours will result in a formal revocation of remote work privileges.",
        "gov_data.txt": "Data Privacy regulations at our organization mandate that all customer personally identifiable information (PII) must be stored using industry-standard AES-256 encryption at rest and TLS 1.3 encryption protocols while in transit. We prioritize the absolute protection of sensitive user data, aligning our entire technical infrastructure with international compliance frameworks including GDPR, CCPA, and localized data sovereignty standards. Access to production databases, API endpoints, and live cloud storage buckets is restricted exclusively to essential engineering and DevOps personnel who have successfully completed an advanced multi-step security vetting process. All system access tokens, administrative configuration changes, and granular query logs are automatically fed into a real-time monitoring system, which facilitates continuous security auditing to preemptively identify and neutralize potential vulnerabilities before they can be exploited."
    },
    "data/procurement": {
        "proc_vendor.txt": "Vendor Onboarding procedures require all prospective external suppliers to submit a formal capability statement, at least three verifiable professional references, and valid business registration certifications prior to the initiation of any contract drafting phase. Following the successful completion of the initial digital documentation review, the procurement department will conduct a rigorous on-site facility visit and an independent financial stability audit to ensure that the vendor has the capacity to withstand potential supply chain disruptions. Approved suppliers are subsequently entered into our centralized Enterprise Resource Planning (ERP) ledger for long-term collaboration. This strict vetting and onboarding cycle is designed to ensure rigorous quality control, adherence to ethical sourcing compliance, and long-term supply chain reliability, effectively minimizing our operational dependencies on unverified or high-risk third-party entities.",
        "proc_order.txt": "All internal Purchase Order Requests must be submitted through our secure centralized procurement portal no later than 14 business days prior to the expected delivery or execution date. Any single expenditure request exceeding a financial threshold of $5,000 mandates the initiation of a competitive bidding process, requiring the procurement officer to collect and formally attach a minimum of three independent, comparable vendor quotes. Each request must be accompanied by an itemized cost breakdown, comprehensive technical specifications, and the explicit digital signature of the respective Department Head. Incomplete or sub-standard applications are automatically flagged by our automated system and returned to the initiator to prevent administrative delays and ensure that all budget allocations are strictly aligned with approved fiscal quarter targets.",
        "proc_contract.txt": "Formal Master Service Agreement (MSA) renewal negotiations must actively commence at least 90 days prior to the expiration date of any currently active contractual agreement. The assigned procurement lead is formally tasked with evaluating the external vendor's historical performance metrics against the Key Performance Indicators (KPIs) outlined in the original contract document. If, during this performance review, a vendor is found to have fallen below an 85% satisfaction score regarding delivery timelines, service availability, or SLA compliance, the procurement department is authorized to formally freeze all renewal discussions. In such cases, the service category will immediately be opened up to a public competitive tender process to identify a replacement provider that can better meet our organizational quality and efficiency requirements."
    },
    "data/important": {
        "fin_q1_review.txt": "CONFIDENTIAL: INTERNAL ADMIN ACCESS ONLY. The Q1 Financial Review indicates an unprecedented operational surplus of $1.2M, driven largely by a 22% reduction in regional logistical overheads and a successful transition to automated cloud-based infrastructure. While general capital expenditure remains stable across most departments, the executive leadership team has earmarked 45% of this surplus for immediate strategic reinvestment into our core R&D division to accelerate AI development projects. This comprehensive strategic report forms the foundational blueprint for the upcoming board of directors meeting, where discretionary budgetary adjustments for the remaining three fiscal quarters will be officially finalized and voted upon. Unauthorized disclosure of these projections is strictly prohibited and constitutes a breach of corporate policy.",
        "fin_bonus.txt": "CONFIDENTIAL: INTERNAL ADMIN ACCESS ONLY. The executive performance bonus distribution matrix for the 2026 fiscal year is tied directly to the achievement of specific, measurable divisional growth metrics and overarching corporate profitability targets. Individual eligibility is evaluated using a complex, weighted scale that factors in annual 360-degree leadership reviews, individual project deliverables, and discretionary budget management performance. Specific percentage allocations, tier payout structures, and associated corporate tax implications are treated as highly confidential information. These details must remain restricted to the executive compensation committee and must not be distributed via email or open messaging channels to the general staff, as such disclosure could undermine our corporate compensation strategy.",
        "fin_audit.txt": "CONFIDENTIAL: INTERNAL ADMIN ACCESS ONLY. The internal financial audit executed during the previous quarter revealed minor, yet concerning, tracking discrepancies in corporate travel expense accounts across three major regional branches. To mitigate this ongoing compliance risk and prevent future accounting errors, the finance department is in the process of deploying an automated AI-driven approval workflow that will flag non-compliant expense receipts in real-time. These tight preventative measures are absolutely vital to maintain our current corporate financial transparency rating and to ensure that we maintain clean records ahead of the upcoming annual mandatory external federal tax audit. Employees found to have repeatedly mismanaged corporate funds will be subject to a formal financial internal investigation."
    }
}

# 1. Cleanup and Create Directories
if os.path.exists('database.db'): 
    os.remove('database.db')
for folder in project_data.keys(): 
    os.makedirs(folder, exist_ok=True)

# 2. Populate Files
for folder, files in project_data.items():
    for name, content in files.items():
        with open(os.path.join(folder, name), 'w') as f: f.write(content)

print("Pumped synthetic data into data folders.")